### ISSUE TITLE
Syntax Error Near Unexpected Token 'Newline'

### ISSUE THREAD

**Issue by HumanCodingMachine** [arthaud/c2bf#5]
I'm running one of the example C files, and it continually returns a Syntax Error. Any help?

**Comment by arthaud** [comment]
Could you send the command line you used and the error you got? I just tried on `examples/bf_compiler.c` and that works for me.

**Comment by HumanCodingMachine** [comment]
I've realized my error. I ran <DIR> instead of DIR, which was my problem. I added the < tags at the end. *facepalm*
